services:
  zms-ra-ingest:
    image: ghcr.io/nsfcuswiftpass/zms-ra-ingest:latest
    container_name: zms-ra-ingest
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./sources.json:/app/sources.json:ro
      - /zms/certs/intermediate-g2.crt:/usr/local/share/ca-certificates/intermediate-g2.crt:ro
    environment:
      - SSL_CERT_FILE=/usr/local/share/ca-certificates/intermediate-g2.crt
    networks:
      - zms-service-local-dev-net

networks:
  zms-service-local-dev-net:
    external: true
